#!/usr/bin/env python3
# https://boto3.readthedocs.io/en/latest/reference/services/organizations.html#client

import boto3
import sys
# input = sys.argv[1]
client = boto3.client('organizations')

response = client.list_accounts(
    # NextToken='listAccounts'
)

# print(type(json_response))
print(response['Accounts'])
